# Generated by Django 6.0.3 on 2026-03-14 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='identity',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='identity',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identity',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='father_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identity',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='identity_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License')], max_length=50),
        ),
        migrations.AlterField(
            model_name='identity',
            name='mother_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identity',
            name='nationality',
            field=models.CharField(default='Indian', max_length=100),
        ),
        migrations.CreateModel(
            name='IdentityMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('previous_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.identity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
